DROP INDEX IF EXISTS IX_Instances_RuntimeStatus;
DROP INDEX IF EXISTS IX_Instances_CreatedTime;
DROP INDEX IF EXISTS IX_Instances_Name;
DROP TABLE IF EXISTS Instances;
DROP TABLE IF EXISTS History;
DROP TABLE IF EXISTS NewEvents;
DROP TABLE IF EXISTS NewTasks;